---

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true

extends:
  - 'airbnb-base'

parserOptions:
  ecmaVersion: latest

rules:
  no-console: 0
  no-underscore-dangle: [ 2, { "allow": [ "__filename", "__dirname" ] } ]